namespace PaymentAPI.Helpers
{
    public class Constants
    {
        public const string SecurityCode = "...jwtSecureCode...";
        public const string SqlConnectionString = "SqlServerConnStr";
        public const string InvalidRequest = "Invalid Client Request";
        public const string TransactionTriggered = "User Triggered Transaction!";
        public const string InProgress = "InProgress";
        public const string Done = "Done";
        public const string Exchange = "Exchange";    
        public const string TransactionUpdated = "Transaction Updated!";
        public const string TransactionDone = "Customer Transaction Done!!";
        public const string AutoGenerated = "Auto Generated";
        public const string EmailSettingsUsername ="EmailSettings:Username";
        public const string EmailSettingsPassword="EmailSettings:Password";
        public const string SmtpServer = "EmailSettings:SmtpServer";
    }
}
