using MailKit.Net.Smtp;
using MimeKit;
using PaymentAPI.Helpers;
using PaymentAPI.Models;

namespace PaymentAPI.UtilityService
{
    public class EmailService : IEmailService
    {
        private readonly IConfiguration _config;

        public EmailService(IConfiguration config)
        {
            _config = config;
        }
        public void SendEmail(EmailModel emailModel)
        {
            var emailMessage = new MimeMessage();
            var from = _config[Constants.EmailSettingsUsername];
            emailMessage.From.Add(new MailboxAddress(Constants.AutoGenerated, from));
            emailMessage.To.Add(new MailboxAddress(emailModel.To, emailModel.To));
            emailMessage.Subject = emailModel.Subject;
            emailMessage.Body = new TextPart(MimeKit.Text.TextFormat.Html)
            {
                Text = string.Format(emailModel.Content)
            };

            using (var client = new SmtpClient())
            {
                try
                {
                    client.Connect(_config[Constants.SmtpServer], 465, true);
                    client.Authenticate(_config[Constants.EmailSettingsUsername], _config[Constants.EmailSettingsPassword]);
                    client.Send(emailMessage);
                }
                catch (Exception ex)
                {
                    throw;
                }
                finally
                {
                    client.Disconnect(true);
                    client.Dispose();
                }
            }

        }
    }
}
